app/Http/routes.php
    Route::get('/coupons/index','AdminController@coupons_index')->name('coupons.index');

    Route::get('/coupons/view','AdminController@coupons_view')->name('coupons.view');

    Route::get('/coupons/delete','AdminController@coupons_delete')->name('coupons.delete');

    Route::get('/coupons/status','AdminController@coupons_status_change')->name('coupons.status');

    // New Coupons Methods ends

    // Custom Push

    Route::get('/custom/push', 'AdminController@custom_push')->name('push');

    Route::post('/custom/push', 'AdminController@custom_push_save')->name('send.push');

    // Admin email Methods start

    Route::get('/email/form','AdminController@mailcamp_create')->name('mailcamp.create');

    Route::post('/email/form/action','AdminController@email_send_process')->name('email.success');

    // Admin email Methods ends


    // Admin templates Methods begins

    Route::get('/templates', 'AdminController@templates_index')->name('templates.index');

    Route::get('templates/create/', 'AdminController@templates_create')->name('templates.create');

    Route::get('templates/edit/', 'AdminController@templates_edit')->name('templates.edit');

    Route::post('templates/save/', 'AdminController@templates_save')->name('templates.save');

    Route::get('templates/view/', 'AdminController@templates_view')->name('templates.view');

    // Admin templates Methods ends

    Route::get('help' , 'AdminController@help')->name('help');


    // Exports tables

    Route::get('/users/export/', 'AdminExportController@users_export')->name('users.export');

    Route::get('/moderators/export/', 'AdminExportController@moderators_export')->name('moderators.export');

    Route::get('/videos/export/', 'AdminExportController@videos_export')->name('videos.export');

    Route::get('/subscription/payment/export/', 'AdminExportController@subscription_export')->name('subscription.export');

    Route::get('/payperview/payment/export/', 'AdminExportController@payperview_export')->name('payperview.export');

    // Exports tables methods ends

    Route::get('/videos/download/status', 'AdminController@admin_videos_download_status')->name('admin_videos.download_status');
   
    Route::get('/users/referrals/index', 'AdminController@users_referrals_index')->name('users.referrals.index');

    Route::get('user_payments/view' , 'AdminController@user_payments_view')->name('user_payments.view');

    Route::get('ppv_payments/view' , 'AdminController@ppv_payments_view')->name('ppv_payments.view');
    
    Route::get('server_status_view' , 'AdminController@server_status_view')->name('server_status_view');


});

Route::group(['middleware' => ['AdminMiddleware' , 'admin'] , 'prefix' => 'admin'  , 'as' => 'admin.'], function() {

    // Admins CRUD Operations

    Route::get('admins/create', 'AdminController@admins_create')->name('admins.create');

    Route::get('admins/edit', 'AdminController@admins_edit')->name('admins.edit');

    Route::get('admins/view', 'AdminController@admins_view')->name('admins.view');

    Route::get('admins/status', 'AdminController@admins_status')->name('admins.status');

    Route::get('admins/index', 'AdminController@admins_index')->name('admins.list');

    Route::get('admins/delete', 'AdminController@admins_delete')->name('admins.delete');

    Route::post('admins/save', 'AdminController@admins_save')->name('admins.save');

    // Languages

    Route::get('/languages/index', 'LanguageController@languages_index')->name('languages.index'); 

    Route::get('/languages/download/', 'LanguageController@languages_download')->name('languages.download'); 

    Route::get('/languages/create', 'LanguageController@languages_create')->name('languages.create');
    
    Route::get('/languages/edit', 'LanguageController@languages_edit')->name('languages.edit');

    Route::get('/languages/status', 'LanguageController@languages_status_change')->name('languages.status');   

    Route::post('/languages/save', 'LanguageController@languages_save')->name('languages.save');

    Route::get('/languages/delete', 'LanguageController@languages_delete')->name('languages.delete');

    Route::get('/languages/set_default', 'LanguageController@languages_set_default')->name('languages.set_default');

    /** | * | * | * | * | * | * | REVENUES SECTION START | * | * | * | * | * | * | */

    Route::get('revenue/dashboard', 'AdminController@revenue_dashboard')->name('revenue.dashboard');

    // New User Payment details
    
    Route::get('user/payments' , 'AdminController@user_payments')->name('user.payments');

    Route::get('ajax/subscription/payments', 'AdminController@ajax_subscription_payments')->name('ajax.user-payments');

    // Video payments

    Route::get('user/video-payments' , 'AdminController@video_payments')->name('user.video-payments');

    Route::get('ajax/video/payments','AdminController@ajax_video_payments')->name('ajax.video-payments');


    /** | * | * | * | * | * | * | REVENUES SECTION END | * | * | * | * | * | * | */


    /** * * * * * * * * * * * * * Subscriptions section start * * * * * * * * * * * * * */

    // New subscriptions Methods begins

    Route::get('/subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

    Route::get('/subscription/save', 'AdminController@users_subscriptions_save')->name('users.subscriptions.save');

    Route::get('/subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

    Route::get('/subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

    Route::post('/subscriptions/create', 'AdminController@subscriptions_save')->name('subscriptions.save');

    Route::get('/subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

    Route::get('/subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

    Route::get('/subscriptions/status', 'AdminController@subscriptions_status_change')->name('subscriptions.status.change');

    Route::get('/subscriptions/popular/status', 'AdminController@subscriptions_popular_status')->name('subscriptions.popular.status');

    Route::get('/subscriptions/users', 'AdminController@subscriptions_users')->name('subscriptions.users');

    // New Subscriptions Methods ends

    /** * * * * * * * * * * * * * Subscriptions section end * * * * * * * * * * * * * */


    // Admin account Methods begins
    
    Route::get('/profile', 'AdminController@profile')->name('profile');

    Route::post('/profile/save', 'AdminController@profile_save')->name('save.profile');

    Route::post('/change/password', 'AdminController@change_password')->name('change.password');

    // Admin account Methods ends

    // Admin Settings Methods begins

    Route::get('settings' , 'AdminController@settings')->name('settings');
    
    Route::post('settings' , 'AdminController@settings_save')->name('settings.save');

    Route::post('common-settings_save' , 'AdminController@common_settings_save')->name('common-settings.save');

    Route::post('video-settings_save' , 'AdminController@video_settings_save')->name('video-settings.save');

    // Home page setting url

    Route::get('homepage/settings','AdminController@home_page_settings')->name('homepage.settings');

    Route::get('/settings_generate_json', 'AdminController@settings_generate_json')->name('settings_generate_json'); 

    // Admin Settings Methods ends


    // Admin Pages Methods begin

    Route::get('/pages', 'AdminController@pages_index')->name('pages.index');

    Route::get('/pages/create', 'AdminController@pages_create')->name('pages.create');

    Route::get('/pages/edit', 'AdminController@pages_edit')->name('pages.edit');

    Route::post('/pages/create', 'AdminController@pages_save')->name('pages.save');

    Route::get('/pages/view', 'AdminController@pages_view')->name('pages.view');

    Route::get('/pages/delete', 'AdminController@pages_delete')->name('pages.delete');
    
    // New Pages Methods ends


    // Sub Admins CRUD Operations

    Route::get('sub_admins/index', 'AdminController@sub_admins_index')->name('sub_admins.index');

    Route::get('sub_admins/create', 'AdminController@sub_admins_create')->name('sub_admins.create');

    Route::get('sub_admins/edit', 'AdminController@sub_admins_edit')->name('sub_admins.edit');

    Route::get('sub_admins/view', 'AdminController@sub_admins_view')->name('sub_admins.view');

    Route::get('sub_admins/status', 'AdminController@sub_admins_status')->name('sub_admins.status');

    Route::get('sub_admins/delete', 'AdminController@sub_admins_delete')->name('sub_admins.delete');

    Route::post('sub_admins/save', 'AdminController@sub_admins_save')->name('sub_admins.save');

    //ios control settings

    // Get ios control page
    Route::get('/ios-control','AdminController@ios_control')->name('ios_control');

    //Save the ios control status
    Route::post('/ios-control/save','AdminController@ios_control_save')->name('ios_control.save');

    Route::get('ajax/users_index', 'AdminController@ajax_users_index')->name('ajax.users_index');

    Route::get('videos/set-position', 'AdminController@admin_videos_set_position')->name('admin_videos_set_position');

});

Route::group(['middleware' => ['SubAdminMiddleware', 'admin'], 'prefix' => 'subadmin', 'as' => 'subadmin.'], function () {

    Route::get('/', 'SubAdminController@dashboard')->name('dashboard');

    Route::get('subadmin/profile', 'SubAdminController@profile')->name('profile');

});

Route::get('/user/searchall' , 'ApplicationController@search_video')->name('search');

Route::any('/user/search' , 'ApplicationController@search_all')->name('search-all');

// Categories and single video 

Route::get('categories', 'UserController@all_categories')->name('user.categories');

Route::get('category/{id}', 'UserController@category_videos')->name('user.category');

app/Language.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Language extends Model
{
    //
}

resources/views/admin/languages/_form.blade.php
<form  action="{{Setting::get('admin_delete_control') == YES  ? '#' : route('admin.languages.save') }}" method="POST" enctype="multipart/form-data" role="form">

	<div class="box-body">

		<input type="hidden" name="language_id" value="{{ $language_details->id }}">

	    <div class="form-group">
	        <label for="folder_name">{{ tr('short_name') }}</label>
	        <input type="text" class="form-control" name="folder_name" id="folder_name" placeholder="{{ tr('example_language') }}" required maxlength="4" value="{{ old('folder_name') ?: $language_details->folder_name }}">
	    </div>

	    <div class="form-group">
	        <label for="language">{{ tr('language') }}</label>
	        <div>
	            <input type="text" class="form-control" name="language" id="language" placeholder="{{ tr('example_language2') }}" required maxlength="64" value="{{ old('language') ?: $language_details->language }}">
	        </div>
	    </div>

	    <div class="form-group">
	        <label for="auth_file">{{ tr('auth_file') }}</label>
	        <input type="file" id="auth_file" name="auth_file" accept=".php" placeholder="{{ tr('picture') }}">
	        <br>	        
	        <ul class="ace-thumbnails clearfix" style="list-style-type: none;">
	            <li>	                
	                <div class="tools tools-bottom">
	                    <a href="{{ route('admin.languages.download', ['folder_name'=> $language_details->folder_name, 'file_name'=>'auth']) }}">
	                        <i class="fa fa-download"></i> {{tr('download_file')}}
	                    </a>
	                </div>
	            </li>
	        </ul>
	    </div>

	    <div class="form-group">
	        <label for="messages_file">{{ tr('messages_file') }}</label>
	        <input type="file" id="messages_file" name="messages_file"  accept=".php" placeholder="{{ tr('picture') }}">
	         <br>
	        <ul class="ace-thumbnails clearfix" style="list-style-type: none;">
	            <li>	                
	                <div class="tools tools-bottom">
	                    <a href="{{ route('admin.languages.download', ['folder_name'=>$language_details->folder_name, 'file_name'=>'messages']) }}">
	                        <i class="fa fa-download"></i> {{tr('download_file')}}
	                    </a>
	                </div>
	            </li>
	        </ul>
	    </div>

	    <div class="form-group">
	        <label for="pagination_file">{{ tr('pagination_file') }}</label>
	        <input type="file" id="pagination_file" name="pagination_file" accept=".php" placeholder="{{ tr('picture') }}">
	         <br>
	        <ul class="ace-thumbnails clearfix" style="list-style-type: none;">
	            <li>	                
	                <div class="tools tools-bottom">
	                    <a href="{{ route('admin.languages.download', ['folder_name'=>$language_details->folder_name, 'file_name'=>'pagination']) }}">
	                        <i class="fa fa-download"></i> {{tr('download_file')}}
	                    </a>
	                </div>
	            </li>
	        </ul>
	    </div>

	    <div class="form-group">
	        <label for="passwords_file">{{ tr('passwords_file') }}</label>
	        <input type="file" id="passwords_file" name="passwords_file" accept=".php" placeholder="{{ tr('picture') }}">
	         <br>
	        <ul class="ace-thumbnails clearfix" style="list-style-type: none;">
	            <li>
	                <div class="tools tools-bottom">
	                    <a href="{{ route('admin.languages.download', ['folder_name'=>$language_details->folder_name, 'file_name' => 'passwords']) }}">
	                        <i class="fa fa-download"></i> {{tr('download_file')}}
	                    </a>
	                </div>
	            </li>
	        </ul>
	    </div>

	    <div class="form-group">
	        <label for="validation_file">{{ tr('validation_file') }}</label>
	        <input type="file" id="validation_file" name="validation_file" accept=".php" placeholder="{{ tr('picture') }}">
	         <br>
	        <ul class="ace-thumbnails clearfix" style="list-style-type: none;">
	            <li>	                
	                <div class="tools tools-bottom">
	                    <a href="{{ route('admin.languages.download', ['folder_name' => $language_details->folder_name, 'file_name'=>'validation']) }}">
	                        <i class="fa fa-download"></i> {{tr('download_file')}}
	                    </a>
	                </div>
	            </li>
	        </ul>
	    </div>

	</div>

	<div class="box-footer">

	    <button type="reset" class="btn btn-danger">{{ tr('cancel') }}</button>
	    
	    <button type="submit" class="btn btn-success pull-right" @if(Setting::get('admin_delete_control') == YES ) disabled  @endif>{{tr('submit')}}</button>
	   
	</div>

</form>

resources/views/admin/languages/create.blade.php
@extends('layouts.admin')

@section('title', tr('create_language'))

@section('content-header', tr('languages'))

@section('breadcrumb')
    <li><a href="{{route('admin.languages.index')}}"><i class="fa fa-globe"></i>{{tr('languages')}}</a></li>
    <li class="active"><i class="fa fa-globe"></i>&nbsp; {{tr('create_language')}}</li>
@endsection

@section('content')

  	<div class="row">

	    <div class="col-md-10">
    		
	        <div class="box box-warning">

	            <div class="box-header table-header-theme">
	                <b>{{tr('create_language')}}</b>
	                <a href="{{ route('admin.languages.index') }}" style="float:right" class="btn btn-default">{{tr('view_languages')}}</a>
	            </div>

	            @include('admin.languages._form')

	        </div>

	    </div>

	</div>
   
@endsection

resources/views/admin/languages/edit.blade.php
@extends('layouts.admin')

@section('title', tr('edit_language'))

@section('content-header', tr('edit_language'))

@section('breadcrumb')
    <li><a href="{{route('admin.languages.index')}}"><i class="fa fa-globe"></i>{{tr('languages')}}</a></li>
    <li class="active"><i class="fa fa-globe"></i>&nbsp; {{tr('edit_language')}}</li>
@endsection

@section('styles')

    <link rel="stylesheet" href="{{asset('common/css/imageHover.css')}}">

@endsection

@section('content')

  	<div class="row">

	    <div class="col-md-10">
    		
	        <div class="box box-warning">

	            <div class="box-header table-header-theme">
	                <b>{{tr('edit_language')}}</b>
	                <a href="{{ (Setting::get('admin_delete_control')) ? '#' : route('admin.languages.index')}}" style="float:right" class="btn btn-default">{{tr('languages')}}</a>
	            </div>

	            @include('admin.languages._form')

	        </div>

	    </div>

	</div>
   
@endsection

resources/views/admin/languages/index.blade.php
@extends('layouts.admin')

@section('title', tr('languages'))

@section('content-header', tr('languages'))

@section('breadcrumb')
    <li class="active"><i class="fa fa-globe"></i> {{tr('languages')}}</li>
@endsection

@section('content')

    <div class="row">

        <div class="col-xs-12">
            
            <div class="box box-warning">

                <div class="box-header table-header-theme">
                    <b>{{tr('view_languages')}}</b>
                    <a href="{{route('admin.languages.create')}}" style="float:right" class="btn btn-default"><i class="fa fa-plus"></i>  {{tr('add_language')}}</a>
                </div>

                <div class="box-body">
                    
                    @if(count($languages) != 0)
                    
                    <table id="example1" class="table table-bordered table-striped">

                        <thead>
                            <tr>
                                <th>{{tr('id')}}</th>
                                <th>{{tr('language') }}</th>
                                <th>{{tr('short_name')}}</th>
                                <th>{{tr('auth_file')}}</th>
                                <th>{{tr('messages_file')}}</th>
                                <th>{{tr('pagination_file')}}</th>
                                <th>{{tr('passwords_file')}}</th>
                                <th>{{tr('validation_file')}}</th>
                                <th>{{tr('status')}}</th>
                                <th>{{tr('action')}}</th>
                            </tr>
                        
                        </thead>

                        <tbody>
                                                        
                                @foreach($languages as $i => $language_details)
                               
                                <tr>
                                    <td>{{$i+1}}</td>

                                    <td>{{$language_details->language}}</td>

                                    <td>{{$language_details->folder_name}}</td>

                                    <td>
                                        <a href="{{route('admin.languages.download', ['folder_name' => $language_details->folder_name, 'file_name'=>'auth'] )}}" target="_blank">
                                            {{tr('download_here')}}
                                        </a>

                                    </td>
                                    
                                    <td>
                                        <a href="{{route('admin.languages.download', array('folder_name' => $language_details->folder_name, 'file_name'=>'messages'))}}" target="_blank">
                                            {{tr('download_here')}}
                                        </a>

                                    </td>
                                    
                                    <td>
                                        <a href="{{route('admin.languages.download', array('folder_name'=>$language_details->folder_name, 'file_name'=>'pagination'))}}" target="_blank">
                                            {{tr('download_here')}}
                                        </a>
                                    </td>
                                    
                                    <td>
                                        <a href="{{route('admin.languages.download', array('folder_name'=>$language_details->folder_name, 'file_name'=>'passwords'))}}" target="_blank">
                                            {{tr('download_here')}}
                                        </a>

                                    </td>
                                    
                                    <td>
                                        <a href="{{route('admin.languages.download', array('folder_name'=>$language_details->folder_name, 'file_name'=>'validation'))}}" target="_blank">
                                            {{tr('download_here')}}
                                        </a>

                                    </td>
                                    <td>
                                         @if($language_details->status == APPROVED)
                                            <span class="label label-success">{{tr('active')}}</span>
                                        @else
                                            <span class="label label-warning">{{tr('inactive')}}</span>
                                        @endif
                                    </td>

                                    <td>

                                       <div class="dropdown">
                                        
                                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                {{tr('action')}}
                                                <span class="caret"></span>
                                            </button>

                                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu">
                                                
                                                @if($i != 0)
                                                
                                                    @if(Setting::get('admin_delete_control') == YES)
                                                        <li>
                                                            <a href="javascript:;" class="btn disabled" style="text-align: left"><b><i class="fa fa-edit"></i>&nbsp;{{tr('edit')}}</b></a>
                                                        </li> 

                                                        <li>
                                                            <a href="javascript:;" class="btn disabled" style="text-align: left"><b><i class="fa fa-trash"></i>&nbsp;{{tr('delete')}}</b></a>
                                                        </li>

                                                    @else

                                                        <li>
                                                            <a href="{{route('admin.languages.edit', ['language_id' => $language_details->id ] ) }}"><b><i class="fa fa-edit"></i>&nbsp;{{tr('edit')}}</b></a>
                                                        </li> 

                                                        <li>
                                                            <a onclick="return confirm(&quot;{{ tr('admin_language_delete_confirmation' , $language_details->language) }}&quot;);" href="{{route('admin.languages.delete', ['language_id' => $language_details->id ] ) }}"><b><i class="fa fa-trash"></i>&nbsp;{{tr('delete')}}</b></a>
                                                        </li> 
                                                    @endif            

                                                @endif    

                                                <li>

                                                    @if(count($languages) > 1)

                                                    <a href="{{route('admin.languages.status', ['language_id' => $language_details->id ] )}}"><b>
                                                    @if($language_details->status == APPROVED )
                                                        <i class="fa fa-close"></i>&nbsp;{{tr('inactivate')}}
                                                    @else
                                                        <i class="fa fa-check"></i>&nbsp;{{tr('activate')}}
                                                    @endif
                                                    </b>
                                                    </a>

                                                    @else

                                                     <a href="javascript:void(0);" disabled style="color: red;cursor: no-drop" title="This option will enable when more than one languages !!!">{{$language_details->status == APPROVED ? tr('inactivate') : tr('activate')}}</a>

                                                    @endif
                                                </li>
                                                
                                                @if($language_details->folder_name != Setting::get('default_lang'))
                                                <li>
                                                    <a href="{{route('admin.languages.set_default', ['language_file' => $language_details->folder_name] )}}"><b>
                                                        <i class="fa fa-globe"></i>&nbsp;{{tr('set_default_language')}}
                                                        </b>
                                                    </a>
                                                </li>

                                                @endif

                                            </ul>

                                        </div>

                                    </td>

                                </tr>
                            
                                @endforeach
                           
                        </tbody>

                    </table>

                    @else
                        <h3 class="no-result">{{ tr('no_language_found') }}</h3>
                    @endif
                
                </div>

            </div>
        
        </div>
    
    </div>

@endsection

@if(Session::has('flash_language'))

@section('scripts')

<script type="text/javascript" src="{{asset('common/js/bootbox.min.js')}}"></script>
<script type="text/javascript">

bootbox.confirm("Do you want to reload the page to view default language ?", function(result){ 
    if (result == true) {
        window.location.reload(true);
    }
    console.log('This was logged in the callback: ' + result); 
});

</script>
@endsection

@endif