app/Http/routes.php
<?php

use Illuminate\Support\Facades\Redis;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

if (version_compare(PHP_VERSION, '7.2.0', '>=')) {

    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);

}

Route::get('/clear-cache', function() {

    $exitCode = Artisan::call('config:cache');

   return back();

})->name('clear-cache');

/***********************  UI Routes *********************/


/***********************  UI Routes *********************/

/*********************** TEST ROUTES *********************/

Route::any('/interview_tasks' , 'SampleController@interview_tasks');

Route::get('/test' , 'SampleController@test');

// Route::get('/test' , 'SampleController@test');

Route::post('/test' , 'SampleController@get_image')->name('sample');

Route::get('/export' , 'SampleController@sample_export');

Route::get('/compress' , 'SampleController@compress_image_upload')->name('compress.image');

Route::get('/compress/i' , 'SampleController@compress_image_check');

Route::post('/compress/image' , 'SampleController@getImageThumbnail');

Route::get('/sendpush' , 'SampleController@send_push_notification');

/*********************** TEST ROUTES *********************/

Route::get('/generate/index' , 'ApplicationController@generate_index');

Route::get('generate_player_data' , 'ApplicationController@generate_player_data');

Route::get('admin_videos_auto_clear_cron' , 'ApplicationController@admin_videos_auto_clear_cron');

Route::get('demo_credential_cron' , 'ApplicationController@demo_credential_cron');
    
    
// Used For Version Upgrade - V6.0 Referral Option

Route::get('generate_referral_code', 'ApplicationController@generate_referral_code')->name('generate_referral_code');

Route::get('generate_pages_unique', 'ApplicationController@generate_pages_unique')->name('generate_pages_unique');

/***********************  UI Routes *********************/


Route::get('/embed', 'UserController@embed_video')->name('embed_video');

Route::get('/g_embed', 'UserController@genre_embed_video')->name('genre_embed_video');


// Singout from all devices which is expired account

Route::get('signout/all/devices', 'ApplicationController@signout_all_devices');

Route::get('/email/verification' , 'ApplicationController@email_verify')->name('email.verify');

Route::get('/check/token', 'ApplicationController@check_token_expiry')->name('check_token_expiry');

// Installation

Route::get('/configuration', 'InstallationController@install')->name('installTheme');

Route::get('/system/check', 'InstallationController@system_check_process')->name('system-check');

Route::post('/configuration', 'InstallationController@theme_check_process')->name('install.theme');

Route::post('/install/settings', 'InstallationController@settings_process')->name('install.settings');


// CRON

Route::get('/publish/video', 'ApplicationController@cron_publish_video')->name('publish');

Route::get('/notification/payment', 'ApplicationController@send_notification_user_payment')->name('notification.user.payment');

Route::get('/payment/expiry', 'ApplicationController@user_payment_expiry')->name('user.payment.expiry');

Route::get('/payment/failure' , 'ApplicationController@payment_failure')->name('payment.failure');

Route::get('/automatic/renewal', 'ApplicationController@automatic_renewal_stripe')->name('automatic.renewal');

Route::get('check/download/status', 'ApplicationController@checkDownloadVideoStatus')->name('checkDownloadVideoStatus');

// Generral configuration routes 

Route::post('project/configurations' , 'ApplicationController@configuration_site');


// Static Pages

Route::get('/privacy', 'UserApiController@privacy')->name('user.privacy');

Route::get('/terms_condition', 'UserApiController@terms')->name('user.terms');

Route::get('/static/terms', 'UserApiController@terms')->name('user.terms');

Route::get('/contact', 'UserController@contact')->name('user.contact');

Route::get('/privacy_policy', 'ApplicationController@privacy')->name('user.privacy_policy');

Route::get('/terms', 'ApplicationController@terms')->name('user.terms-condition');

Route::get('/about', 'ApplicationController@about')->name('user.about');

// Video upload 

Route::post('select/sub_category' , 'ApplicationController@select_sub_category')->name('select.sub_category');

Route::post('select/genre' , 'ApplicationController@select_genre')->name('select.genre');

Route::get('/admin-control', 'ApplicationController@admin_control')->name('admin_control');

Route::post('save_admin_control', 'ApplicationController@save_admin_control')->name('save_admin_control');

Route::get('/admin/check_role', 'AdminController@check_role');


Route::get('/', 'AdminController@dashboard')->name('dashboard');


Route::group(['prefix' => 'admin'  , 'as' => 'admin.'], function() {

    Route::get('/', 'AdminController@dashboard')->name('dashboard');

    Route::get('login', 'Auth\AdminAuthController@showLoginForm')->name('login');

    Route::post('login', 'Auth\AdminAuthController@login')->name('login.post');

    Route::get('logout', 'Auth\AdminAuthController@logout')->name('logout');

    // Registration Routes...

    Route::get('register', 'Auth\AdminAuthController@showRegistrationForm');

    Route::post('register', 'Auth\AdminAuthController@register');

    // Password Reset Routes...
    Route::get('password/reset/{token?}', 'Auth\AdminPasswordController@showResetForm');

    Route::post('password/email', 'Auth\AdminPasswordController@sendResetLinkEmail');

    Route::post('password/reset', 'Auth\AdminPasswordController@reset');

    //  Admin User Methods starts

    Route::get('/users', 'AdminController@users_index')->name('users.index');

    Route::get('users/create', 'AdminController@users_create')->name('users.create');

    Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

    Route::post('users/create', 'AdminController@users_save')->name('users.save');

    Route::get('/users/view', 'AdminController@users_view')->name('users.view');

    Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

    Route::get('users/status/change', 'AdminController@users_status_change')->name('users.status.change');
    
    Route::get('/users/verify', 'AdminController@users_verify_status')->name('users.verify');

    Route::get('/users/upgrade', 'AdminController@users_upgrade')->name('users.upgrade');

    Route::any('users/upgrade-disable', 'AdminController@users_upgrade_disable')->name('users.upgrade.disable');

    Route::get('/users/subprofiles', 'AdminController@users_sub_profiles')->name('users.subprofiles');

    Route::get('/users/clear-login', 'AdminController@users_clear_login')->name('users.clear-login');

    Route::get('/uses/subscriptions', 'AdminController@users_subscriptions')->name('subscriptions.plans');

    Route::get('/users/wallet/{id}', 'AdminController@users_wallet')->name('users.wallet');

    //  Admin Users History - admin

    Route::get('/users/history', 'AdminController@users_history')->name('users.history');

    Route::get('users/history/remove', 'AdminController@users_history_remove')->name('users.history.remove');
    
    //  Admin Users Wishlist - admin

    Route::get('/users/wishlist', 'AdminController@users_wishlist')->name('users.wishlist');

    Route::get('/users/wishlist/remove', 'AdminController@users_wishlist_remove')->name('users.wishlist.remove');

    Route::post('/users/subscriptions/disable', 'AdminController@users_auto_subscription_disable')->name('subscriptions.cancel');

    Route::get('/users/subscriptions/enable', 'AdminController@users_auto_subscription_enable')->name('subscriptions.enable');

    //  Admin User Methods Ends

    //  Admin moderators Methods begins

    Route::get('/moderators', 'AdminController@moderators_index')->name('moderators.index');

    Route::get('/moderators/create', 'AdminController@moderators_create')->name('moderators.create');

    Route::get('/moderators/edit', 'AdminController@moderators_edit')->name('moderators.edit');

    Route::post('/moderators/create', 'AdminController@moderators_save')->name('moderators.save');

    Route::get('/moderators/delete', 'AdminController@moderators_delete')->name('moderators.delete');

    Route::get('/moderators/view', 'AdminController@moderators_view')->name('moderators.view');

    Route::get('/moderators/videos','AdminController@moderators_videos')->name('moderators.videos.index');

    Route::get('moderators/status/change', 'AdminController@moderators_status_change')->name('moderators.status.change');


    Route::get('/moderator/videos/{id}','AdminController@moderator_videos')->name('moderator.videos.list');


    Route::get('moderators/redeems', 'AdminController@moderators_redeem_requests')->name('moderators.redeems');

    Route::any('/moderators/payout/invoice', 'AdminController@moderators_redeems_payout_invoice')->name('moderators.payout.invoice');

     Route::post('moderators/payout/direct', 'AdminController@moderators_redeems_payout_direct')->name('moderators.payout.direct');

    Route::any('/moderators/payout/response', 'AdminController@moderators_redeems_payout_response')->name('moderators.payout.response');

    // Redeem Pay from Paypal

    Route::get('moderator/redeem-pay', 'RedeemPaymentController@redeem_pay')->name('moderator.redeem_pay');

    Route::get('moderator/redeem-pay-status', 'RedeemPaymentController@redeem_pay_status')->name('moderator.redeem_pay_status');
    
    // Admin moderators Methods ends


    // Admin Categories Methods begins

    Route::get('/categories', 'AdminController@categories_index')->name('categories.index');

resources/views/admin/admins/_form.blade.php
<div class="row">

    <div class="col-md-10">

        <div class="box box-warning">

            <div class="box-header table-header-theme">
                <b style="font-size:18px;">@yield('title')</b>
                <a href="{{ route('admin.admins.index') }}" class="btn btn-default pull-right">{{ tr('view_admins') }}</a>
            </div>

            <form class="form-horizontal" action="{{  Setting::get('admin_delete_control') == YES ? '#' :  route('admin.admins.save')  }}" method="POST" enctype="multipart/form-data" role="form">

                <div class="box-body">

                    <input type="hidden" name="admin_id" value="{{ $admin_details->id }}">

                    <input type="hidden" name="timezone" value="{{ $admin_details->timezone }}" id="userTimezone">

                    <div class="form-group">
                        <label for="username" class="col-sm-2 control-label">* {{ tr('username') }}</label>

                        <div class="col-sm-10">
                            <input type="text" required name="name" 
                            title="{{ tr('only_alphanumeric') }}" class="form-control" id="username" placeholder="{{ tr('name') }}" value="{{ old('name') ?: $admin_details->name  }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="email" class="col-sm-2 control-label">* {{ tr('email') }}</label>
                        <div class="col-sm-10">
                            <input type="email" maxlength="255" required class="form-control" id="email" name="email" placeholder="{{ tr('email') }}" value="{{ old('email') ?: $admin_details->email }}">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="mobile" class="col-sm-2 control-label">* {{ tr('mobile') }}</label>

                        <div class="col-sm-10">
                            <input type="text" required name="mobile" class="form-control" id="mobile" placeholder="{{ tr('mobile') }}" minlength="4" maxlength="16" pattern="[0-9]{4,16}" value="{{ $admin_details->mobile ? $admin_details->mobile : old('mobile') }}">
                            <br>
                             <small style="color:brown">{{ tr('mobile_note') }}</small>
                        </div>
                    </div>

                    @if(!$admin_details->id)

                    <div class="form-group">
                        <label for="password" class="col-sm-2 control-label">* {{ tr('password') }}</label>

                        <div class="col-sm-10">
                            <input type="password" required name="password" title="{{ tr('password_notes') }}" class="form-control" id="password" placeholder="{{ tr('password') }}" value="{{ old('password') }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="username" class="col-sm-2 control-label">* {{ tr('password_confirmation') }}</label>

                        <div class="col-sm-10">
                            <input type="password" required title="{{ tr('password_notes') }}" name="password_confirmation" class="form-control" id="username" placeholder="{{ tr('password_confirmation') }}" value="{{ old('password_confirmation') }}">
                        </div>
                    </div>


                    @endif

                    <div class="form-group">
                        <label for="description" class="col-sm-2 control-label">* {{ tr('description') }}</label>
                        <div class="col-sm-10">
                           <textarea class="form-control" name="description" placeholder="{{ tr('description') }}">{{  old('description') ?: $admin_details->description  }}</textarea>
                        </div>
                    </div>

                </div>

                <div class="box-footer">
                    <button type="reset" class="btn btn-danger">{{   tr('cancel')   }}</button>        
                    <button type="submit" class="btn btn-success pull-right" @if(Setting::get('admin_delete_control') == YES) disabled @endif) >{{   tr('submit')   }}</button>        
                </div>


            </form>
        
        </div>

    </div>

</div>

resources/views/admin/admins/create.blade.php
@extends('layouts.admin')

@section('title', tr('create_admin'))

@section('content-header', tr('create_admin'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.admins.index')}}"><i class="fa fa-user"></i> {{tr('admins')}}</a></li>
    <li class="active"><i class="fa fa-user-plus"></i> {{tr('create_admin')}}</li>
@endsection

@section('content')

	@include('admin.admins._form')

@endsection

@section('scripts')

<script src="{{asset('assets/js/jstz.min.js')}}"></script>
<script>
    
    $(document).ready(function() {

        var dMin = new Date().getTimezoneOffset();
        var dtz = -(dMin/60);
        // alert(dtz);
        $("#userTimezone").val(jstz.determine().name());
    });

</script>

@endsection

resources/views/admin/admins/edit.blade.php
@extends('layouts.admin')

@section('title', tr('edit_admin'))

@section('content-header', tr('edit_admin'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.admins.index')}}"><i class="fa fa-user"></i> {{tr('admins')}}</a></li>
    <li class="active"><i class="fa fa-user-plus"></i> {{tr('edit_admin')}}</li>
@endsection

@section('content')

	@include('admin.admins._form')

@endsection

@section('scripts')

<script src="{{asset('assets/js/jstz.min.js')}}"></script>
<script>
    
    $(document).ready(function() {

        var dMin = new Date().getTimezoneOffset();
        var dtz = -(dMin/60);
        // alert(dtz);
        $("#userTimezone").val(jstz.determine().name());
    });

</script>

@endsection

resources/views/admin/admins/index.blade.php
@extends('layouts.admin')

@section('title', tr('admins'))

@section('content-header') 

	{{tr('admins')}} 

@endsection

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li class="active"><i class="fa fa-user"></i> {{tr('admins')}}</li>
@endsection

@section('content')

	<div class="row">

        <div class="col-xs-12">
          	
          	<div class="box box-warning">
          	
	          	<div class="box-header table-header-theme">	                
	          		<b style="font-size:18px;">
	          			{{tr('admins')}}
	          		</b>
	               
	                <a href="{{route('admin.admins.create')}}" class="btn btn-default pull-right"><i class="fa fa-plus"></i> {{tr('create_admin')}}</a>
	            </div>
            
	            <div class="box-body">

	            	<div class="table-responsive" style="padding: 35px 0px"> 
	            		
	            		<div class="table table-responsive">
			              	
			              	<table id="example1" class="table table-bordered table-striped ">
								<thead>
								    <tr>
										<th>{{tr('id')}}</th>
										<th>{{tr('username')}}</th>
										<th>{{tr('email')}}</th>
										<th>{{tr('mobile')}}</th>
										<th>{{tr('status')}}</th>
										<th>{{tr('action')}}</th>
								    </tr>
								
								</thead>

								<tbody>

									@foreach($admins as $i => $admin_details)

									    <tr>
									      	<td>{{ $i+1 }}</td>

									      	<td>
									      		<a href="{{route('admin.users.view' , ['user_id' => $admin_details->id])}}">
									      			{{$admin_details->name}}
									      		</a>
									      	</td>

									      	<td>{{$admin_details->email}}</td>	
									      
									      	<td>{{$admin_details->mobile}}</td>
									      	
									      	<td>
										      	@if($admin_details->is_activated)
										      		<span class="label label-success">{{tr('approve')}}</span>
										      	@else
										      		<span class="label label-warning">{{tr('pending')}}</span>
										      	@endif
									     	</td>
									 
									      	<td>
		            							<ul class="admin-action btn btn-default">
		            								<li class="@if($i < 2) dropdown @else dropup @endif">
										                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
										                  {{tr('action')}} <span class="caret"></span>
										                </a>

										                <ul class="dropdown-menu dropdown-menu-right">
										                  	<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.admins.edit' , ['admin_id' => $admin_details->id] )}}">{{tr('edit')}}</a></li>

										                  	<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.admins.view' , ['admin_id' => $admin_details->id]  )}}">{{tr('view')}}</a></li>

										                  	@if($admin_details->is_activated)
										                  		<li role="presentation"><a role="menuitem" onclick="return confirm(&quot;{{$admin_details->name}} - {{tr('admin_decline_confirmation')}}&quot;);" tabindex="-1" href="{{route('admin.admins.status' , ['admin_id' => $admin_details->id] )}}"> {{tr('decline')}}</a></li>
										                  	 @else 
										                  	 	<li role="presentation"><a role="menuitem" onclick="return confirm(&quot;{{$admin_details->name}} - {{tr('admin_approve_confirmation')}}&quot;);" tabindex="-1" href="{{route('admin.users.status.change' , ['admin_id' => $admin_details->id]  )}}"> 
										                  		{{tr('approve')}} </a></li>
										                  	@endif

										                  
										                  	<li role="presentation" class="divider"></li>

										                    <li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.admins.delete' , ['admin_id' => $admin_details->id] )}}">{{tr('delete')}}</a></li>
										                  	

										                </ul>

		              								</li>

		            							</ul>
									      	
									      	</td>

									    </tr>

									@endforeach
								
								</tbody>
							
							</table>
						
						</div>						
						
					</div>

	            </div>

          	</div>

        </div>
    
    </div>

@endsection

resources/views/admin/admins/view.blade.php
@extends('layouts.admin')

@section('title', tr('view_admin'))

@section('content-header', tr('view_admin'))

@section('breadcrumb')
    <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i>{{ tr('home') }}</a></li>
    <li><a href="{{ route('admin.admins.index') }}"><i class="fa fa-user"></i> {{ tr('admins') }}</a></li>
    <li class="active"><i class="fa fa-user-plus"></i> {{ tr('view_admin') }}</li>
@endsection

@section('content')

	<style type="text/css">
		.timeline::before {
		    content: '';
		    position: absolute;
		    top: 0;
		    bottom: 0;
		    width: 0;
		    background: #fff;
		    left: 0px;
		    margin: 0;
		    border-radius: 0px;
		}
	</style>

	<div class="row">

		<div class="col-md-10 col-md-offset-1">

    		<div class="box box-widget widget-user-2">

            	<div class="widget-user-header bg-gray">
            		<div class="pull-left">
	              		<div class="widget-user-image">

	                		<img class="img-circle" src=" @if($admin_details->picture) {{ $admin_details->picture }} @else {{ asset('admin-css/dist/img/avatar.png') }} @endif" alt="{{ $admin_details->name }}">
	              		</div>

	              		<h3 class="widget-user-username">{{ $admin_details->name }} </h3>
	      				<h5 class="widget-user-desc">{{ tr('user') }}</h5>
      				</div>
      				<div class="pull-right">
      					<a href="{{ route('admin.admins.edit' , ['admin_id' => $admin_details->id] ) }}" class="btn btn-sm btn-warning">{{ tr('edit') }}</a>
      				</div>
      				<div class="clearfix"></div>
            	</div>	
            	
            	<div class="box-footer no-padding">
            		
            		<div class="col-md-6">

	              		<ul class="nav nav-stacked">
			                <li><a href="#">{{ tr('username') }} <span class="pull-right">{{ $admin_details->name }}</span></a></li>

			                <li><a href="#">{{ tr('email') }} <span class="pull-right">{{ $admin_details->email }}</span></a></li>

			                <li><a href="#">{{ tr('mobile') }} <span class="pull-right">{{ $admin_details->mobile }}</span></a></li>

			                <li>
			                	<a href="#">{{ tr('status') }} 
			                		<span class="pull-right">
			                			@if($admin_details->is_activated) 
							      			<span class="label label-success">{{ tr('approved') }}</span>
							       		@else 
							       			<span class="label label-warning">{{ tr('pending') }}</span>
							       		@endif
			                		</span>
			                	</a>
			                </li>

			                <li>
			                	<a href="#">{{ tr('description') }}
			                		<br>
			                		<br>
			                		<p class="">{{ $admin_details->description }}</span></p>
			                	</a>
			                </li>		             
	              		</ul>

            		</div>

	            	<div class="col-md-6">

	            		<ul class="nav nav-stacked">

			                <li><a href="#">{{ tr('timezone') }} <span class="pull-right">{{ $admin_details->timezone ? $admin_details->timezone : "-" }}</span></a></li>

			                <li><a href="#">{{ tr('created_at') }} <span class="pull-right">{{ convertTimeToUSERzone($admin_details->created_at, Auth::guard('admin')->user()->timezone, 'd-m-Y H:i a') }}</span></a></li>

			                <li><a href="#">{{ tr('updated_at') }} <span class="pull-right">{{ convertTimeToUSERzone($admin_details->updated_at, Auth::guard('admin')->user()->timezone, 'd-m-Y H:i a') }}</span></a></li>

	              		</ul>

	            	</div>

          		</div>

          	</div>

		</div>

    </div>

@endsection