app/Http/routes.php
Route::get('/compress' , 'SampleController@compress_image_upload')->name('compress.image');

Route::get('/compress/i' , 'SampleController@compress_image_check');

Route::post('/compress/image' , 'SampleController@getImageThumbnail');

Route::get('/sendpush' , 'SampleController@send_push_notification');

/*********************** TEST ROUTES *********************/

Route::get('/generate/index' , 'ApplicationController@generate_index');

Route::get('generate_player_data' , 'ApplicationController@generate_player_data');

Route::get('admin_videos_auto_clear_cron' , 'ApplicationController@admin_videos_auto_clear_cron');

Route::get('demo_credential_cron' , 'ApplicationController@demo_credential_cron');
    
    
// Used For Version Upgrade - V6.0 Referral Option

Route::get('generate_referral_code', 'ApplicationController@generate_referral_code')->name('generate_referral_code');

Route::get('generate_pages_unique', 'ApplicationController@generate_pages_unique')->name('generate_pages_unique');

/***********************  UI Routes *********************/


Route::get('/embed', 'UserController@embed_video')->name('embed_video');

Route::get('/g_embed', 'UserController@genre_embed_video')->name('genre_embed_video');


// Singout from all devices which is expired account

Route::get('signout/all/devices', 'ApplicationController@signout_all_devices');

Route::get('/email/verification' , 'ApplicationController@email_verify')->name('email.verify');

Route::get('/check/token', 'ApplicationController@check_token_expiry')->name('check_token_expiry');

// Installation

Route::get('/configuration', 'InstallationController@install')->name('installTheme');

Route::get('/system/check', 'InstallationController@system_check_process')->name('system-check');

Route::post('/configuration', 'InstallationController@theme_check_process')->name('install.theme');

Route::post('/install/settings', 'InstallationController@settings_process')->name('install.settings');


// CRON

Route::get('/publish/video', 'ApplicationController@cron_publish_video')->name('publish');

Route::get('/notification/payment', 'ApplicationController@send_notification_user_payment')->name('notification.user.payment');

Route::get('/payment/expiry', 'ApplicationController@user_payment_expiry')->name('user.payment.expiry');

Route::get('/payment/failure' , 'ApplicationController@payment_failure')->name('payment.failure');

Route::get('/automatic/renewal', 'ApplicationController@automatic_renewal_stripe')->name('automatic.renewal');

Route::get('check/download/status', 'ApplicationController@checkDownloadVideoStatus')->name('checkDownloadVideoStatus');

// Generral configuration routes 

Route::post('project/configurations' , 'ApplicationController@configuration_site');


// Static Pages

Route::get('/privacy', 'UserApiController@privacy')->name('user.privacy');

Route::get('/terms_condition', 'UserApiController@terms')->name('user.terms');

Route::get('/static/terms', 'UserApiController@terms')->name('user.terms');

Route::get('/contact', 'UserController@contact')->name('user.contact');

Route::get('/privacy_policy', 'ApplicationController@privacy')->name('user.privacy_policy');

Route::get('/terms', 'ApplicationController@terms')->name('user.terms-condition');

Route::get('/about', 'ApplicationController@about')->name('user.about');

// Video upload 

Route::post('select/sub_category' , 'ApplicationController@select_sub_category')->name('select.sub_category');

Route::post('select/genre' , 'ApplicationController@select_genre')->name('select.genre');

Route::get('/admin-control', 'ApplicationController@admin_control')->name('admin_control');

Route::post('save_admin_control', 'ApplicationController@save_admin_control')->name('save_admin_control');

Route::get('/admin/check_role', 'AdminController@check_role');


Route::get('/', 'AdminController@dashboard')->name('dashboard');


Route::group(['prefix' => 'admin'  , 'as' => 'admin.'], function() {

    Route::get('/', 'AdminController@dashboard')->name('dashboard');

    Route::get('login', 'Auth\AdminAuthController@showLoginForm')->name('login');

    Route::post('login', 'Auth\AdminAuthController@login')->name('login.post');

    Route::get('logout', 'Auth\AdminAuthController@logout')->name('logout');

    // Registration Routes...

    Route::get('register', 'Auth\AdminAuthController@showRegistrationForm');

    Route::post('register', 'Auth\AdminAuthController@register');

    // Password Reset Routes...
    Route::get('password/reset/{token?}', 'Auth\AdminPasswordController@showResetForm');

    Route::post('password/email', 'Auth\AdminPasswordController@sendResetLinkEmail');

    Route::post('password/reset', 'Auth\AdminPasswordController@reset');

    //  Admin User Methods starts

    Route::get('/users', 'AdminController@users_index')->name('users.index');

    Route::get('users/create', 'AdminController@users_create')->name('users.create');

    Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

    Route::post('users/create', 'AdminController@users_save')->name('users.save');

    Route::get('/users/view', 'AdminController@users_view')->name('users.view');

    Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

    Route::get('users/status/change', 'AdminController@users_status_change')->name('users.status.change');
    
    Route::get('/users/verify', 'AdminController@users_verify_status')->name('users.verify');

    Route::get('/users/upgrade', 'AdminController@users_upgrade')->name('users.upgrade');

    Route::any('users/upgrade-disable', 'AdminController@users_upgrade_disable')->name('users.upgrade.disable');

    Route::get('/users/subprofiles', 'AdminController@users_sub_profiles')->name('users.subprofiles');

    Route::get('/users/clear-login', 'AdminController@users_clear_login')->name('users.clear-login');

    Route::get('/uses/subscriptions', 'AdminController@users_subscriptions')->name('subscriptions.plans');

    Route::get('/users/wallet/{id}', 'AdminController@users_wallet')->name('users.wallet');

    //  Admin Users History - admin

    Route::get('/users/history', 'AdminController@users_history')->name('users.history');

    Route::get('users/history/remove', 'AdminController@users_history_remove')->name('users.history.remove');
    
    //  Admin Users Wishlist - admin

    Route::get('/users/wishlist', 'AdminController@users_wishlist')->name('users.wishlist');

    Route::get('/users/wishlist/remove', 'AdminController@users_wishlist_remove')->name('users.wishlist.remove');

    Route::post('/users/subscriptions/disable', 'AdminController@users_auto_subscription_disable')->name('subscriptions.cancel');

    Route::get('/users/subscriptions/enable', 'AdminController@users_auto_subscription_enable')->name('subscriptions.enable');

    //  Admin User Methods Ends

    //  Admin moderators Methods begins

    Route::get('/moderators', 'AdminController@moderators_index')->name('moderators.index');

    Route::get('/moderators/create', 'AdminController@moderators_create')->name('moderators.create');

    Route::get('/moderators/edit', 'AdminController@moderators_edit')->name('moderators.edit');

    Route::post('/moderators/create', 'AdminController@moderators_save')->name('moderators.save');

    Route::get('/moderators/delete', 'AdminController@moderators_delete')->name('moderators.delete');

    Route::get('/moderators/view', 'AdminController@moderators_view')->name('moderators.view');

    Route::get('/moderators/videos','AdminController@moderators_videos')->name('moderators.videos.index');

    Route::get('moderators/status/change', 'AdminController@moderators_status_change')->name('moderators.status.change');


    Route::get('/moderator/videos/{id}','AdminController@moderator_videos')->name('moderator.videos.list');


    Route::get('moderators/redeems', 'AdminController@moderators_redeem_requests')->name('moderators.redeems');

    Route::any('/moderators/payout/invoice', 'AdminController@moderators_redeems_payout_invoice')->name('moderators.payout.invoice');

     Route::post('moderators/payout/direct', 'AdminController@moderators_redeems_payout_direct')->name('moderators.payout.direct');

    Route::any('/moderators/payout/response', 'AdminController@moderators_redeems_payout_response')->name('moderators.payout.response');

    // Redeem Pay from Paypal

    Route::get('moderator/redeem-pay', 'RedeemPaymentController@redeem_pay')->name('moderator.redeem_pay');

    Route::get('moderator/redeem-pay-status', 'RedeemPaymentController@redeem_pay_status')->name('moderator.redeem_pay_status');
    
    // Admin moderators Methods ends


    // Admin Categories Methods begins

    Route::get('/categories', 'AdminController@categories_index')->name('categories.index');

    Route::get('/categories/create', 'AdminController@categories_create')->name('categories.create');

    Route::get('/categories/edit', 'AdminController@categories_edit')->name('categories.edit');

    Route::post('/categories/create', 'AdminController@categories_save')->name('categories.save');

    Route::get('/categories/delete', 'AdminController@categories_delete')->name('categories.delete');

    Route::get('/categories/view', 'AdminController@categories_view')->name('categories.view');

    Route::get('categories/status/change', 'AdminController@categories_status_change')->name('categories.status.change');

    // USER HOME PAGE DISPLAY
    
    Route::get('categories/home/status', 'AdminController@categories_home_status')->name('categories.home.status');

    // Admin Categories Methods ends

    // Admin Sub Categories Methods begins

    Route::get('/sub_categories/{category_id?}', 'AdminController@sub_categories_index')->name('sub_categories.index');

    Route::get('/sub_categories/create/{category_id?}', 'AdminController@sub_categories_create')->name('sub_categories.create');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\Helper;

class Category extends Model
{
	public function subCategory()
    {
        return $this->hasMany('App\SubCategory');
    }

    public function genre()
    {
        return $this->hasMany('App\Genre');
    }

    public function adminVideo()
    {
        return $this->hasMany('App\AdminVideo');
    }

	public static function boot()
    {
        //execute the parent's boot method 
        parent::boot();

        //delete your related models here, for example
        static::deleting(function($categories)
        {
            foreach($categories->subCategory as $sub_category)
            {  

                foreach($sub_category->subCategoryImage as $image) {

                    Helper::delete_picture($image->picture,'/uploads/images/');  

                    $image->delete();
                } 

                $sub_category->delete();
            } 

            foreach($categories->adminVideo as $video) {           

                deleteVideoAndImages($video);

                $video->delete();
            } 

            foreach($categories->genre as $genre) {                

                Helper::delete_picture($genre->image,'/uploads/images/');
                
                if($genre->video) {

                    Helper::delete_picture($genre->video, '/uploads/videos/original/');   

                }

                if ($genre->subtitle) {
                    
                    Helper::delete_picture($genre->subtitle, SUBTITLE_PATH);

                }  
  

                $genre->delete();
            } 

        });	

    }

    
}

resources/views/admin/categories/_form.blade.php
<form action="{{ Setting::get('admin_delete_control') == YES ? '#' : route('admin.categories.save') }}" method="POST" enctype="multipart/form-data" role="form">

    <div class="box-body">

        <input type="hidden" name="category_id" value="{{ $category_details->id }}">

        <div class="form-group col-md-5">

            <label for="name">* {{ tr('name') }}</label>
            
            <input type="text" required class="form-control" title="{{ tr('only_alphanumeric') }}" value="{{  old('name') ?: $category_details->name }}" id="name" name="name" placeholder="{{ tr('enter') }} {{ tr('category') }}">

        </div>

        <div class="checkbox col-md-7">

            <label for="picture"></label>

            <label>
                <input type="checkbox" name="is_series" value="1" class="minimal-red" @if($category_details->is_series) checked @endif> {{ tr('is_series') }}
            </label>

        </div>

        <div class="form-group col-md-12">

            <label for="picture">* {{tr('picture')}}</label>
            
            <br>

            @if($category_details->picture != '')

                <img id="image_preview" style="width: 100px;height: 100px;" src="{{ $category_details->picture }}">

            @else 

                <img id="image_preview" style="width: 100px;height: 100px;display: none;">

            @endif

            <br>

            <input type="file" accept="image/jpeg,image/png" id="picture" name="picture" placeholder="{{tr('picture')}}" onchange="loadFile(this,'image_preview')" @If(!$category_details->id) required @endif>

            <p class="help-block">{{tr('image_validate')}} {{tr('image_square')}}</p>

        </div>

        <div class="clearfix"></div>

    </div>

    <div class="box-footer">

        <button type="reset" class="btn btn-danger">{{ tr('cancel') }}</button>

        <button type="submit" class="btn btn-success pull-right" @if(Setting::get('admin_delete_control') == YES ) disabled @endif >{{ tr('submit') }}</button>
    </div>

</form>

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('title', tr('add_category'))

@section('content-header', tr('categories'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.categories.index')}}"><i class="fa fa-suitcase"></i> {{tr('categories')}}</a></li>
    <li class="active">{{tr('add_category')}}</li>
@endsection

@section('styles')

    <link rel="stylesheet" href="{{asset('admin-css/plugins/iCheck/all.css')}}">

@endsection

@section('content')

    <div class="row">

        <div class="col-md-10">

            <div class="box box-warning">

                <div class="box-header table-header-theme">
                    <b style="font-size:18px;">{{tr('add_category')}}</b>
                    <a href="{{route('admin.categories.index')}}" class="btn btn-default pull-right">{{tr('view_categories')}}</a>
                </div>


                @include('admin.categories._form')

            </div>

        </div>

    </div>

@endsection

@section('scripts')

   <script src="{{asset('admin-css/plugins/iCheck/icheck.min.js')}}"></script>

    <script type="text/javascript">

        function loadFile(event,id){

            $('#'+id).show();

            var reader = new FileReader();

            reader.onload = function(){

                var output = document.getElementById(id);

                output.src = reader.result;
            };

            reader.readAsDataURL(event.files[0]);
        }

    </script>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('title', tr('edit_category'))

@section('content-header', tr('categories'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.categories.index')}}"><i class="fa fa-suitcase"></i> {{tr('categories')}}</a></li>
    <li class="active">{{tr('edit_category')}}</li>
@endsection


@section('styles')

    <link rel="stylesheet" href="{{asset('admin-css/plugins/iCheck/all.css')}}">

@endsection

@section('content')

    <div class="row">

        <div class="col-md-10">
            
            <div class="box box-warning">

                <div class="box-header table-header-theme">
                    <b style="font-size:18px;">{{tr('edit_category')}}</b>
                    <a href="{{route('admin.categories.create')}}" class="btn btn-default pull-right"><i class="fa fa-plus"></i> {{tr('add_category')}}</a>
                </div>

                @include('admin.categories._form')

            </div>

        </div>

    </div>

@endsection

@section('scripts')

<script src="{{asset('admin-css/plugins/iCheck/icheck.min.js')}}"></script>

    <script type="text/javascript">

        function loadFile(event,id){

            $('#'+id).show();

            var reader = new FileReader();

            reader.onload = function(){

                var output = document.getElementById(id);

                output.src = reader.result;
            };

            reader.readAsDataURL(event.files[0]);
        }

    </script>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('title', tr('view_categories'))

@section('content-header', tr('categories'))

@section('breadcrumb')
    <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i>{{ tr('home') }}</a></li>
    <li class="active"><i class="fa fa-suitcase"></i> {{ tr('categories') }}</li>
@endsection

@section('content')

	<div class="row">

        <div class="col-xs-12">
			
          	<div class="box box-warning">

	          	<div class="box-header table-header-theme">
	                <b style="font-size:18px;">{{ tr('view_categories') }}</b>
	                <a href="{{ route('admin.categories.create') }}" class="btn btn-default pull-right"><i class="fa fa-plus"></i> {{ tr('add_category') }}</a>
	            </div>
	            
	            <div class="box-body">

	            	@if(count($categories) > 0)

		              	<table id="datatable-withoutpagination" class="table table-bordered table-striped">

							<thead>
							    <tr>
							      <th>{{ tr('id') }}</th>
							      <th>{{ tr('category') }}</th>
							      <th>{{ tr('picture') }}</th>
								  <th>{{ tr('total_videos') }}</th>
							      <th>{{ tr('sub_categories') }}</th>
							      <th>{{ tr('is_series') }}</th>
							      <th>{{ tr('status') }}</th>
							      <th>{{ tr('action') }}</th>
							    </tr>
							</thead>

							<tbody>

								@foreach($categories as $i => $category_details)

								    <tr>
								      	<td>{{ showEntries($_GET, $i+1) }}</td>

								      	<td><a href="{{ route('admin.categories.view' , ['category_id' => $category_details->id] ) }}">
								      		{{ $category_details->name }}</a>
								      	</td>

								      	<td>
		                                	<img style="height: 30px;" src="{{ $category_details->picture }}">
		                            	</td>

										<td>
											@if($category_details->videos_count > 0)
		                                	<a href="{{route('admin.videos', ['category_id' => $category_details->id])}}">{{$category_details->videos_count}}</a>
		                                	@else
		                                		-
		                                	@endif
		                            	</td>

		                            	<td>
		                            		<a href="{{ route('admin.sub_categories.index' , ['category_id' => $category_details->id] ) }}">
		                            		{{ $category_details->subCategory ? count($category_details->subCategory) : '0' }}</a>
		                            	</td>

		                            	<td>
								      		@if($category_details->is_series ==YES )
								      			<span class="label label-success">{{ tr('yes') }}</span>
								       		@else
								       			<span class="label label-warning">{{ tr('no') }}</span>
								       		@endif
								       	</td>

								      	<td>
								      		@if($category_details->is_approved == CATEGORY_APPROVED)
								      			<span class="label label-success">{{ tr('approved') }}</span>
								       		@else
								       			<span class="label label-warning">{{ tr('pending') }}</span>
								       		@endif
								        </td>

								      	<td>
	            							<ul class="admin-action btn btn-default">
	            								
	            								<li class="{{ $i <= 1 ? 'dropdown' : 'dropup' }}">
	            								
									                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
									                  {{ tr('action') }} <span class="caret"></span>
									                </a>
									                <ul class="dropdown-menu dropdown-menu-right">
									                	<li>
									                		<a href="{{ route('admin.categories.view' , ['category_id' => $category_details->id] ) }}">{{ tr('view') }}</a>
									                	</li>

									                	@if(Setting::get('admin_delete_control') == YES )

										                  	<li role="presentation">
		                                                        <a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{ tr('edit') }}</a>
		                                                   	</li>
										                  	<li role="presentation">
												                 <a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{ tr('delete') }}</a>
												            </li>

	                                                    @else
		                                                   	<li role="presentation">
		                                                        <a role="menuitem" tabindex="-1" href="{{ route('admin.categories.edit' , ['category_id' => $category_details->id] ) }}">{{ tr('edit') }}</a>
		                                                    </li>
										                  	<li role="presentation">
										                  		<a role="menuitem" tabindex="-1" onclick="return confirm(&quot;{{ tr('category_delete_confirmation' , $category_details->name) }}&quot;);" href="{{ route('admin.categories.delete' , ['category_id' => $category_details->id] ) }}">{{ tr('delete') }}</a>
										                  	</li>

									                  	@endif
														<li class="divider" role="presentation"></li>

									                  	@if($category_details->is_approved == CATEGORY_APPROVED )
									                  		<li role="presentation"><a role="menuitem" tabindex="-1" onclick="return confirm(&quot;{{ tr('category_decline_confirmation' , $category_details->name) }}&quot;);" href="{{ route('admin.categories.status.change', ['category_id' => $category_details->id] ) }}">{{ tr('decline') }}</a></li>
									                  	@else
									                  		<li role="presentation"><a role="menuitem" tabindex="-1" onclick="return confirm(&quot;{{ tr('category_approve_confirmation' , $category_details->name) }}&quot;);" href="{{ route('admin.categories.status.change', ['category_id' => $category_details->id]) }}">{{ tr('approve') }}</a></li>
									                  	@endif

									                  	<li class="divider" role="presentation"></li>

									                  	<li role="presentation"><a role="menuitem" tabindex="-1" href="{{ route('admin.sub_categories.create', ['category_id' => $category_details->id] ) }}">{{ tr('add_sub_category') }}</a></li>

									                  	<li role="presentation"><a role="menuitem" tabindex="-1" href="{{ route('admin.sub_categories.index', ['category_id' => $category_details->id] ) }}">{{ tr('view_sub_categories') }}</a></li>

									                  	<li class="divider" role="presentation"></li>

									                  	<li role="presentation"><a role="menuitem" tabindex="-1" href="{{ route('admin.videos', ['category_id' => $category_details->id] ) }}">{{ tr('videos') }}</a></li>
									                </ul>

	              								</li>

	            							</ul>
	            							
								        </td>

								    </tr>

								@endforeach

							</tbody>
						
						</table>

						<div align="right" id="paglink"><?php echo $categories->links(); ?></div>
					@else
						<h3 class="no-result">{{ tr('no_result_found') }}</h3>
					@endif
	            
	            </div>

          	</div>
        </div>
    </div>

@endsection

resources/views/admin/categories/view.blade.php
@extends('layouts.admin')

@section('title', tr('view_category'))

@section('content-header', tr('categories'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.categories.index')}}"><i class="fa fa-suitcase"></i> {{tr('categories')}}</a></li>
    <li class="active"><i class="fa fa-eye"></i>&nbsp;{{tr('view_categories')}}</li>
@endsection

@section('content')

	<style type="text/css">
		.timeline::before {
		    content: '';
		    position: absolute;
		    top: 0;
		    bottom: 0;
		    width: 0;
		    background: #fff;
		    left: 0px;
		    margin: 0;
		    border-radius: 0px;
		}
	</style>

	
	<div class="row">

		<div class="col-md-10 col-md-offset-1">
			
			<div class="box box-warning">

				<div class="box-header table-header-theme">
					<h3 class="box-title pull-left"><b>{{tr('view_category')}}</b></h3> 
					<a href="{{route('admin.categories.index')}}" class="btn btn-default pull-right">{{tr('categories')}}</a>

            	</div>

				<div class="box-body">

					<div class="col-md-6">

						<strong><i class="fa fa-book margin-r-5"></i> {{tr('name')}}</strong>
						<span class="pull-right">{{$category_details->name}}</span>
						<hr>

						<strong><i class="fa fa-book margin-r-5"></i> {{tr('status')}}</strong>
						
			      			@if($category_details->is_approved == CATEGORY_APPROVED )
				      			<a href="#" class="btn  btn-xs btn-success pull-right">{{tr('approved')}}</a>
				      		@else
			      				<a href="#" class="btn  btn-xs btn-danger pull-right">{{tr('declined')}}</a>
				      		@endif
						<hr>

				      	<strong><i class="fa fa-book margin-r-5"></i> {{tr('is_series')}}</strong>	
			      			@if($category_details->is_series)
			      				<a href="#" class="btn btn-xs btn-success pull-right" >{{tr('yes')}}</a>
				      		@else
				      			<a href="#" class="btn btn-xs btn-danger pull-right"> {{tr('no')}}</a>
				      		@endif
						<hr>

						<strong><i class="fa fa-calendar margin-r-5"></i> {{tr('sub_categories')}}</strong>
						<a href="{{route('admin.sub_categories.index' , ['category_id' => $category_details->id] )}}" class="pull-right">
		                {{$category_details->subCategory ? count($category_details->subCategory) : '0'}}</a>
		                <hr>

						<strong><i class="fa fa-calendar margin-r-5"></i> {{tr('created_at')}}</strong>						
						<p class="text-muted pull-right">{{convertTimeToUSERzone($category_details->created_at, Auth::guard('admin')->user()->timezone, 'd-m-Y H:i a')}}</p>
						<hr>

						<strong><i class="fa fa-calendar margin-r-5"></i> {{tr('updated_at')}}</strong>
						<p class="text-muted pull-right">{{convertTimeToUSERzone($category_details->updated_at, Auth::guard('admin')->user()->timezone, 'd-m-Y H:i a')}}</p>

					</div>

					<div class="col-md-6">

                        <div class="header">

                            <h4><b>{{tr('picture')}}</b></h4>

                            <img src="{{$category_details->picture}}" style="width: 100%;max-height:300px;">

                        </div>					

					</div>

				</div>

				<div class="box-footer">

	            	<center>
		      			
						@if(Setting::get('admin_delete_control') == YES)

                            <a role="button" href="javascript:;" class="btn btn-sm btn-warning btn disabled" style="text-align: left"><i class="fa fa-edit"></i>{{tr('edit')}}
                            </a>

                            @if($category_details->is_approved == CATEGORY_APPROVED)
		                  		<a  class="btn btn-sm btn-warning" onclick="return confirm(&quot;{{tr('category_decline_confirmation' , $category_details->name)}}&quot;);" href="javascript:;"><i class="fa fa-close"></i>{{tr('decline')}}</a>
		                  	@else
		                  		<a class="btn btn-sm btn-success" onclick="return confirm(&quot;{{tr('category_approve_confirmation' , $category_details->name)}}&quot;);" href="javascript:;" ><i class="fa fa-check"></i>{{tr('approve')}}</a>
		                  	@endif

		                  	<a class="btn btn-sm btn-danger" href="javascript:;"  onclick="return confirm(&quot;{{tr('category_delete_confirmation' , $category_details->name)}}&quot;);"><i class="fa fa-trash"></i>&nbsp;	{{tr('delete')}}
		                  	</a>
                        @else
                            <a class="btn btn-sm btn-warning" role="menuitem" tabindex="-1" href="{{route('admin.categories.edit' , ['category_id' => $category_details->id] )}}"><b> <i class="fa fa-edit"></i>&nbsp;{{tr('edit')}}</b></a>

                            @if($category_details->is_approved == CATEGORY_APPROVED)
		                  		<a  class="btn btn-sm btn-warning" onclick="return confirm(&quot;{{tr('category_decline_confirmation' , $category_details->name)}}&quot;);" href="{{route('admin.categories.status.change' , ['category_id' => $category_details->id] )}}"><b> <i class="fa fa-close"></i>&nbsp;</b>{{tr('decline')}}</a>
		                  	@else
		                  		<a class="btn btn-sm btn-success" onclick="return confirm(&quot;{{tr('category_approve_confirmation' , $category_details->name)}}&quot;);" href="{{route('admin.categories.status.change' , ['category_id' => $category_details->id ])}}"><b> <i class="fa fa-check"></i>&nbsp;</b>{{tr('approve')}}</a>
		                  	@endif

		                  	<a class="btn btn-sm btn-danger" onclick="return confirm(&quot;{{tr('category_delete_confirmation' , $category_details->name)}}&quot;);" href="{{route('admin.categories.delete' , ['category_id' => $category_details->id] )}}"><b> <i class="fa fa-trash"></i>&nbsp;</b>{{tr('delete')}}</a>
		                  	</a>

                        @endif

                    	<a class="btn btn-sm btn-info" href="{{route('admin.sub_categories.create', ['category_id' => $category_details->id] )}}">{{tr('add_sub_category')}}</a>

	                  	<a class="btn btn-sm btn-info" href="{{route('admin.sub_categories.index', ['category_id' => $category_details->id] )}}">{{tr('view_sub_categories')}}</a>

	                  	<a class="btn btn-sm btn-success" href="{{route('admin.videos', ['category_id' => $category_details->id] )}}"><b> <i class="fa fa-video-camera"></i>&nbsp;</b>{{tr('videos')}}</a></a>
	                </center>
				</div>

			</div>
			<!-- /.box -->
		</div>

    </div>

@endsection